# Variables
PYTHON = python3
PIP = pip3
TESTS = tests
SRC = src
VENV = venv

# Cibles par défaut
.PHONY: all install venv activate clean lint test run

all: install lint test

# Crée et active l'environnement virtuel
venv:
	$(PYTHON) -m venv $(VENV)

activate:
	@echo "Activez l'environnement virtuel avec 'source $(VENV)/bin/activate'"

# Installe les dépendances
install: venv
	source $(VENV)/bin/activate && $(PIP) install -r requirements.txt

# Vérifie le style de code avec flake8
lint:
	source $(VENV)/bin/activate && flake8 $(SRC)

# Exécute les tests
test:
	source $(VENV)/bin/activate && pytest $(TESTS)

# Nettoie les fichiers générés
clean:
	rm -rf $(VENV)
	find . -type f -name '*.pyc' -delete
	find . -type d -name '__pycache__' -delete

# Exécute le programme principal
run:
	source $(VENV)/bin/activate && $(PYTHON) $(SRC)/main.py
