# Variables
PYTHON = python3
PIP = pip
VENV_DIR = venv
SRC = main.py
REQUIREMENTS = requirements.txt

# Cibles par défaut
.PHONY: all install venv activate clean run

all: install

# Crée et active l'environnement virtuel
venv:
	$(PYTHON) -m venv $(VENV_DIR)

activate:
	@echo "Pour activer l'environnement virtuel, utilisez 'source $(VENV_DIR)/bin/activate'"

# Installe les dépendances
install: venv
	. $(VENV_DIR)/bin/activate && $(PIP) install -r $(REQUIREMENTS)

# Nettoie les fichiers générés
clean:
	rm -rf $(VENV_DIR)
	find . -type f -name '*.pyc' -delete
	find . -type d -name '__pycache__' -delete

# Exécute le programme principal
run:
	. $(VENV_DIR)/bin/activate && $(PYTHON) $(SRC)
